
services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - web
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi_app
    networks:
      - web
    restart: always

networks:
  web:
    driver: bridge
