apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradebot
  labels:
    app: tradebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tradebot
  template:
    metadata:
      labels:
        app: tradebot
    spec:
      containers:
      - name: tradebot
        image: us-central1-docker.pkg.dev/inspired-oath-441023-v1/docker-repo/chat_bot:v.0.1
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: tradebot-env